{
  "formatVersion": "1.1",
  "component": {
    "group": "com.hm.iou.lifecycle.plugin",
    "module": "modify",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "modify-1.0.0.jar",
          "url": "modify-1.0.0.jar",
          "size": 22828,
          "sha512": "cedb6e71b52c437ac638060020bc7bf302b7e28332ef3f25e8efcdb521ac1bb96e6d52d3a6716ecfb797e79949830dc9b1477e3502228524f0e5f15c63cc27a5",
          "sha256": "397cdf09f71a2046ef5610435d1f7b2690a763358a110fb127098a049cebcfdd",
          "sha1": "ca68f28db4034c966ca9c67466fa3b60fefa5918",
          "md5": "c4056a502236f7caa67235775c123999"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.10"
          }
        },
        {
          "group": "commons-io",
          "module": "commons-io",
          "version": {
            "requires": "2.8.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "8.1.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.1"
          }
        }
      ],
      "files": [
        {
          "name": "modify-1.0.0.jar",
          "url": "modify-1.0.0.jar",
          "size": 22828,
          "sha512": "cedb6e71b52c437ac638060020bc7bf302b7e28332ef3f25e8efcdb521ac1bb96e6d52d3a6716ecfb797e79949830dc9b1477e3502228524f0e5f15c63cc27a5",
          "sha256": "397cdf09f71a2046ef5610435d1f7b2690a763358a110fb127098a049cebcfdd",
          "sha1": "ca68f28db4034c966ca9c67466fa3b60fefa5918",
          "md5": "c4056a502236f7caa67235775c123999"
        }
      ]
    }
  ]
}
